version: '3'

services:
  ml_app:
    build: .
    command: >
      bash -c 'python manage.py migrate &&
      python manage.py runserver 0:80'
    working_dir: /code/
    ports:
     - "8000:80"
    volumes:
     - .:/code
    env_file:
      - ml_app.env